@startuml REG_Helper_ER
left to right direction

entity User {
  * student_id : varchar <<PK>>
  --
  firstname : varchar
  lastname : varchar
  profile_image : varchar
  email : varchar
  role : UserRole
  department : varchar
  faculty : varchar
  created_at : timestamp
  updated_at : timestamp
}

entity UserOauthProvider {
  * id : uuid <<PK>>
  --
  provider : OauthProvider
  * student_id : varchar <<FK>>
}

entity Transcript {
  * id : uuid <<PK>>
  --
  url : varchar
  created_at : timestamp
  updated_at : timestamp
  --
  student_id : varchar <<FK>>
}

entity Course {
  * course_id : varchar <<PK>>
  --
  name_en : varchar
  name_th : varchar
  description_en : varchar
  description_th : varchar
  credit : int
  credit_str : varchar
  group : CourseGroup
  subgroup : CourseSubGroup
  created_at : timestamp
  updated_at : timestamp
}

entity Section {
  * id : uuid <<PK>>
  --
  name : varchar
  day : varchar
  room : varchar
  year : int
  semester: int
  limit : int
  count : int
  midterm_exam_date : timestamp
  final_exam_date : timestamp
  type : CourseType
  start_at : timestamp
  end_at : timestamp
  condition: varchar
  created_at : timestamp
  updated_at : timestamp
  course_id : varchar <<FK>>
}

entity Teacher {
  * id : uuid <<PK>>
  --
  firstname_en : varchar
  lastname_en : varchar
  firstname_th : varchar
  lastname_th : varchar
  created_at : timestamp
  updated_at : timestamp
}

entity SectionTeacher {
  * id : uuid <<PK>>
  --
  created_at : timestamp
  updated_at : timestamp
  section_id : uuid <<FK>>
  teacher_id : uuid <<FK>>
}

entity UserCourse {
  * id : uuid <<PK>>
  --
  grade : Grade
  created_at : timestamp
  updated_at : timestamp
  student_id : varchar <<FK>>
  course_id : varchar <<FK>>
}

entity Skill {
  * id : uuid <<PK>>
  --
  name_en : varchar
  name_th : varchar
  created_at : timestamp
  updated_at : timestamp
}

entity StudyMaterial {
  * id : uuid <<PK>>
  -- 
  file_path : varchar
  created_at : timestamp
  updated_at :  timestamp
  --
  course_id : varchar <<FK>>
  student_id : varchar <<FK>>
}

entity LikedReview {
  * id : uuid <<FK>>
  --
  created_at : timestamp
  updated_at : timestamp
  --
  student_id : varchar <<FK>>
  review_id : uuid <<FK>>
}

entity Review {
  * id : uuid <<FK>>
  --
  content : text
  rating : int
  created_at : timestamp
  updated_at : timestamp
  --
  student_id : varchar <<FK>>
  course_id : varchar <<FK>>
}

entity Job {
  * id : uuid <<PK>>
  --
  name_en : varchar
  name_th : varchar
  created_at : timestamp
  updated_at : timestamp
}

entity SkillJobMapping {
  * id : uuid <<PK>>
  --
  from : varchar
  from_th : varchar
  from_type : varchar
  to : varchar
  to_th : varchar
  to_type : varchar
  weight : int
  created_at : timestamp
  updated_at : timestamp
  --
  job_id : varchar <<FK>>
  skill_id : uuid <<FK>>
}

entity SkillCourseMapping {
  * id : uuid <<PK>>
  --
  from : varchar
  from_th : varchar
  from_type : varchar
  to : varchar
  to_th : varchar
  to_type : varchar
  weight : int
  created_at : timestamp
  updated_at : timestamp
  --
  course_id : varchar <<FK>>
  skill_id : uuid <<FK>>
}

enum CourseGroup {
  GENED
  SPECIFIC
  FREE_ELECTIVE
}

enum OauthProvider {
  GOOGLE
}

enum CourseSubGroup {
  FREE_ELEC
  FUND
  LANG
  FAC_SPEC
  GENED_ELEC
  CORE
  REQUIRED
  ELEC_REQ
  ALT_STUDY
  MAJOR_ELEC
}

enum UserRole {
  ADMIN
  USER
}

enum CourseType {
  LECTURE
  PRACTICE
}

enum Grade {
  A
  B_PLUS
  B
  C_PLUS
  C
  D_PLUS
  D
  F
  W
  S
  U
}

User ||--o{ Transcript
User ||--|| UserOauthProvider
User ||--o{ UserCourse
Course ||--o{ UserCourse
Course ||--o{ Section
Course ||--o{ SkillCourseMapping
Skill ||--o{ SkillCourseMapping
Skill ||--o{ SkillJobMapping
Job ||--o{ SkillJobMapping
Section ||--o{ SectionTeacher
Teacher ||--o{ SectionTeacher
User ||--o{ Review
User ||-o{ LikedReview
Review ||--o{ LikedReview
Course ||--o{ Review
User ||--o{ StudyMaterial


@enduml
